dist: xenial
language: cpp
compiler: gcc
branches:
  only:
    - main
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

before_deploy:
  - sed -i "s/__VERSION__/$TRAVIS_BUILD_NUMBER/g" bintray-descriptor.json
  - cat bintray-descriptor.json

deploy:
  skip_cleanup: true
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
